/* Shared country metadata and the single WhatsApp number field used by the
 * join, profile, onboarding, and preference surfaces. Raw input stays in the
 * form until it is submitted to the protected backend. */
import { COUNTRY_METADATA } from "./country-flags.js";
const PHONE_EXAMPLE_ROWS = [
  ["GH","Ghana","+233","🇬🇭","024 123 4567"],["LR","Liberia","+231","🇱🇷","077 123 4567"],["NG","Nigeria","+234","🇳🇬","080 1234 5678"],["SN","Senegal","+221","🇸🇳","77 123 45 67"],["SL","Sierra Leone","+232","🇸🇱","076 123 456"],["GM","Gambia","+220","🇬🇲","301 2345"],["CI","Côte d’Ivoire","+225","🇨🇮","07 12 34 56 78"],["CM","Cameroon","+237","🇨🇲","6 71 23 45 67"],["KE","Kenya","+254","🇰🇪","0712 345678"],["UG","Uganda","+256","🇺🇬","0712 345678"],["TZ","Tanzania","+255","🇹🇿","0712 345678"],["ZA","South Africa","+27","🇿🇦","082 123 4567"],["ZM","Zambia","+260","🇿🇲","097 1234567"],["ZW","Zimbabwe","+263","🇿🇼","071 234 5678"],["RW","Rwanda","+250","🇷🇼","078 123 456"],["ET","Ethiopia","+251","🇪🇹","091 123 4567"],["EG","Egypt","+20","🇪🇬","010 1234 5678"],["MA","Morocco","+212","🇲🇦","0612 345678"],["IN","India","+91","🇮🇳","09876 54321"],["PK","Pakistan","+92","🇵🇰","0300 1234567"],["AE","United Arab Emirates","+971","🇦🇪","050 123 4567"],["SA","Saudi Arabia","+966","🇸🇦","050 123 4567"],["FR","France","+33","🇫🇷","06 12 34 56 78"],["DE","Germany","+49","🇩🇪","0151 23456789"],["IT","Italy","+39","🇮🇹","312 345 6789"],["ES","Spain","+34","🇪🇸","612 345 678"],["GB","United Kingdom","+44","🇬🇧","07123 456789"],["NL","Netherlands","+31","🇳🇱","06 12345678"],["BE","Belgium","+32","🇧🇪","0470 12 34 56"],["CH","Switzerland","+41","🇨🇭","078 123 45 67"],["TR","Turkey","+90","🇹🇷","0532 123 45 67"],["BR","Brazil","+55","🇧🇷","(11) 91234-5678"],["CO","Colombia","+57","🇨🇴","300 1234567"],["MX","Mexico","+52","🇲🇽","55 1234 5678"],["PE","Peru","+51","🇵🇪","987 654 321"],["US","United States","+1","🇺🇸","(202) 555-0123"],["CA","Canada","+1","🇨🇦","204 555 0123"],["AU","Australia","+61","🇦🇺","0412 345 678"],["NZ","New Zealand","+64","🇳🇿","021 123 4567"],["SG","Singapore","+65","🇸🇬","8123 4567"],["ID","Indonesia","+62","🇮🇩","0812 3456 789"],["TH","Thailand","+66","🇹🇭","081 234 5678"],["VN","Vietnam","+84","🇻🇳","091 234 5678"],["JP","Japan","+81","🇯🇵","090 1234 5678"],["KR","South Korea","+82","🇰🇷","010 1234 5678"],["PT","Portugal","+351","🇵🇹","912 345 678"],["SE","Sweden","+46","🇸🇪","070 123 45 67"],["NO","Norway","+47","🇳🇴","412 34 567"],["DK","Denmark","+45","🇩🇰","20 12 34 56"],["PL","Poland","+48","🇵🇱","512 345 678"],["UA","Ukraine","+380","🇺🇦","050 123 4567"],["RU","Russia","+7","🇷🇺","912 345-67-89"],["IL","Israel","+972","🇮🇱","050 123 4567"],["QA","Qatar","+974","🇶🇦","3312 3456"],["GH","Ghana","+233","🇬🇭","024 123 4567"]
].filter((row,index,array)=>array.findIndex(candidate=>candidate[0]===row[0])===index).map(([iso,name,callingCode,flag,example])=>({iso,name,callingCode,flag,example}));

const phoneExamples = new Map(PHONE_EXAMPLE_ROWS.map(country=>[country.iso,country.example]));
export const PHONE_COUNTRIES = COUNTRY_METADATA.map(country=>({iso:country.iso2,name:country.name,callingCode:country.callingCode,flag:country.flag,example:phoneExamples.get(country.iso2)||""}));
const defaultPhoneCountry = PHONE_COUNTRIES.find(country=>country.iso==="GH") || PHONE_COUNTRIES[0];
function phoneCountryHint(country) {
  return country.example ? `Example: ${country.callingCode} ${country.example}. Your selected country can be corrected at any time.` : `Country calling code: ${country.callingCode}. Enter the national number assigned by your provider.`;
}
export function phoneCountry(iso) { return PHONE_COUNTRIES.find(country=>country.iso===String(iso||"").toUpperCase()) || defaultPhoneCountry; }
export function renderWhatsAppPhoneField(prefix="join", profile={}) {
  const selected=phoneCountry(profile.countryCode), choices=PHONE_COUNTRIES.map(country=>`<button type="button" class="wa-country-option" data-wa-country="${country.iso}" data-wa-prefix="${country.callingCode}" data-wa-label="${country.flag} ${country.name} ${country.callingCode}"><span>${country.flag}</span><strong>${country.name}</strong><small>${country.callingCode}</small></button>`).join("");
  return `<div class="field full-width wa-phone-field" data-wa-phone-field="${prefix}"><label for="${prefix}-wa-number">WhatsApp number</label><p class="wa-phone-supporting-text">Add your WhatsApp number to continue onboarding, receive application updates and connect with your Be the Change community.</p><div class="wa-phone-picker"><button type="button" class="wa-country-trigger" data-wa-country-trigger="${prefix}" aria-expanded="false"><span data-wa-country-flag>${selected.flag}</span><span data-wa-country-name>${selected.name}</span><span data-wa-country-code>${selected.callingCode}</span></button><input id="${prefix}-wa-country-search" class="wa-country-search" data-wa-country-search="${prefix}" placeholder="Search country" autocomplete="off" aria-label="Search country code" /><div class="wa-country-list" data-wa-country-list="${prefix}" role="listbox">${choices}</div><input type="hidden" data-wa-country-code-value="${prefix}" value="${selected.iso}" /><input type="hidden" data-wa-calling-code-value="${prefix}" value="${selected.callingCode}" /><input id="${prefix}-wa-number" data-wa-local-number="${prefix}" inputmode="tel" autocomplete="tel" value="${profile.localNumber||""}" placeholder="${selected.example||"Local phone number"}" aria-describedby="${prefix}-wa-help ${prefix}-wa-feedback" /></div><div id="${prefix}-wa-help" class="micro-note">${phoneCountryHint(selected)}</div><div id="${prefix}-wa-feedback" class="wa-phone-feedback" data-wa-phone-feedback="${prefix}" role="status"></div><div class="wa-phone-options"><label><input type="checkbox" data-wa-primary-phone="${prefix}" ${profile.isPrimaryPhone?"checked":""} /> This is also my primary phone number</label><label><input type="checkbox" data-wa-no-whatsapp="${prefix}" ${profile.whatsappAvailable===false?"checked":""} /> I do not use WhatsApp</label></div><p class="wa-phone-use">We use this only for requested onboarding, essential service updates, support replies, and optional messages you separately consent to. <a href="#privacy">Read communication preferences</a>.</p><div class="wa-consent-options"><label><input type="checkbox" data-wa-service-consent="${prefix}" ${profile.serviceConsent?"checked":""} /> I agree to receive essential Be the Change service messages on WhatsApp.</label><small>Verification, application progress, requested reminders, payment or order status, requested invitations, and support replies.</small><label><input type="checkbox" data-wa-marketing-consent="${prefix}" ${profile.marketingConsent?"checked":""} /> I would also like to receive optional news, programs and opportunities on WhatsApp.</label><small>News, training, grants, events, offers, and community announcements. Marketing consent is separate and optional.</small></div></div>`;
}
export function readWhatsAppPhoneField(prefix="join") {
  const root=document.querySelector(`[data-wa-phone-field="${prefix}"]`); if(!root)return null;
  const noWhatsApp=root.querySelector(`[data-wa-no-whatsapp="${prefix}"]`)?.checked===true;
  const localNumber=root.querySelector(`[data-wa-local-number="${prefix}"]`)?.value?.trim()||"";
  return { countryCode:root.querySelector(`[data-wa-country-code-value="${prefix}"]`)?.value||"", callingCode:root.querySelector(`[data-wa-calling-code-value="${prefix}"]`)?.value||"", localNumber, isPrimaryPhone:root.querySelector(`[data-wa-primary-phone="${prefix}"]`)?.checked===true, whatsappAvailable:noWhatsApp?false:(localNumber?true:null), service:root.querySelector(`[data-wa-service-consent="${prefix}"]`)?.checked===true, marketing:root.querySelector(`[data-wa-marketing-consent="${prefix}"]`)?.checked===true, source:prefix };
}
export function bindWhatsAppPhoneField(prefix="join", onChange=()=>{}) {
  const root=document.querySelector(`[data-wa-phone-field="${prefix}"]`); if(!root)return;
  const search=root.querySelector(`[data-wa-country-search="${prefix}"]`), list=root.querySelector(`[data-wa-country-list="${prefix}"]`), trigger=root.querySelector(`[data-wa-country-trigger="${prefix}"]`);
  const updateList=()=>{const query=(search?.value||"").toLowerCase();root.querySelectorAll(".wa-country-option").forEach(option=>{option.hidden=Boolean(query&&!option.dataset.waLabel.toLowerCase().includes(query));});};
  search?.addEventListener("input",updateList); trigger?.addEventListener("click",()=>{const open=root.classList.toggle("is-open");trigger.setAttribute("aria-expanded",String(open));if(open)search?.focus();});
  root.querySelectorAll(".wa-country-option").forEach(option=>option.addEventListener("click",()=>{const country=phoneCountry(option.dataset.waCountry);root.querySelector(`[data-wa-country-code-value="${prefix}"]`).value=country.iso;root.querySelector(`[data-wa-calling-code-value="${prefix}"]`).value=country.callingCode;root.querySelector("[data-wa-country-flag]").textContent=country.flag;root.querySelector("[data-wa-country-name]").textContent=country.name;root.querySelector("[data-wa-country-code]").textContent=country.callingCode;root.querySelector(`[data-wa-local-number="${prefix}"]`).placeholder=country.example||"Local phone number";root.querySelector(`#${prefix}-wa-help`).textContent=phoneCountryHint(country);root.classList.remove("is-open");trigger?.setAttribute("aria-expanded","false");onChange();}));
  root.querySelectorAll("input").forEach(input=>input.addEventListener("input",onChange)); root.querySelectorAll("input[type=checkbox]").forEach(input=>input.addEventListener("change",onChange));
}
